import { Link, NavLink, useNavigate, useLocation } from 'react-router-dom';
import { Search, Heart, MessageSquare, Cloud, Code2, Layers, Database, Shield, Users, List, PenLine, UserRound, ArrowRight } from 'lucide-react';
import { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { categories, categoryName } from '../data/categories';
export function Logo(){return <span className="logo"><span className="logo-mark" aria-hidden="true">≈</span>난기류</span>;}
export function Header(){const {user,logout}=useAuth();const navigate=useNavigate();const [q,setQ]=useState(''),[error,setError]=useState('');return <header><div className="header-inner"><Link to="/" aria-label="난기류 홈"><Logo/></Link><nav aria-label="주 메뉴"><NavLink to="/posts">커뮤니티</NavLink><Link to="/posts?type=question">Q&A</Link><Link to="/posts?type=blog">기술블로그</Link></nav><form className="global-search" role="search" onSubmit={e=>{e.preventDefault();navigate(`/posts?q=${encodeURIComponent(q)}`);}}><Search size={18}/><input aria-label="게시글, 태그, 사용자 검색" placeholder="게시글, 태그, 사용자 검색..." value={q} onChange={e=>setQ(e.target.value)}/><button className="sr-only">검색</button></form><Link className="button primary header-write" to="/posts/new"><PenLine size={16}/>글쓰기</Link>{user?<><Link className="avatar" to="/profile" aria-label="내 프로필"><UserRound size={19}/></Link><button className="header-logout" onClick={async()=>{try{await logout();navigate('/');}catch(e){setError(e.message);}}}>로그아웃</button></>:<Link className="header-login" to="/auth">로그인</Link>}</div>{error&&<div role="alert" className="error">{error}</div>}</header>;}
export function Footer(){return <footer><div><Link to="/"><Logo/></Link><span>개발자를 위한 지식 공유 및 성장 커뮤니티</span><small>함께 배우고, 질문하고, 성장해요.</small></div></footer>;}
const icons={code:Code2,layers:Layers,database:Database,cloud:Cloud,shield:Shield,users:Users,message:MessageSquare};
export function CategoryIcon({id,size=20}){const Icon=icons[id]||Code2;return <Icon size={size}/>;}
export function CategorySidebar({active=''}){return <aside className="panel category-sidebar"><small>카테고리</small><Link className={!active?'selected':''} to="/posts"><List size={20}/>전체 게시글</Link>{categories.map(c=><Link key={c.id} className={active===c.id?'selected':''} to={`/posts?category=${c.id}`}><CategoryIcon id={c.icon}/>{c.name}</Link>)}<Link className="qa-box" to="/posts?type=question"><strong>Q&A 바로가기 <ArrowRight size={16}/></strong><p>해결되지 않는 에러나 아키텍처 고민을 동료 개발자들과 나눠보세요.</p></Link></aside>;}
export const dateLabel=value=>new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium'}).format(new Date(value));
export function PostCard({post,compact=false}){return <article className={`post-card ${compact?'compact':''}`}><div className="post-meta"><span className="avatar small">{post.author.nickname.slice(0,1).toUpperCase()}</span><span>{post.author.nickname}</span><span className="muted">· {dateLabel(post.createdAt)}</span><span className="post-counts"><span><Heart size={17}/>{post.likeCount}</span><span><MessageSquare size={17}/>{post.commentCount}</span></span></div><Link className="post-title" to={`/posts/${post.id}`}>{post.title}</Link><div className="tags"><Link to={`/posts?category=${post.category}`}>{categoryName(post.category)}</Link>{post.tags.map(t=><Link key={t} to={`/posts?q=${encodeURIComponent(t)}`}>#{t}</Link>)}</div></article>;}
export function AsyncState({state,children}){if(state.loading)return <div className="panel state" role="status">불러오는 중...</div>;if(state.error)return <div className="panel state"><p className="error" role="alert">{state.error.message}</p><button onClick={state.reload}>다시 시도</button></div>;return children;}
export function Empty({children='아직 게시글이 없습니다.'}){return <div className="panel state muted">{children}</div>;}
export function Protected({children}){const {user,loading,error,refresh}=useAuth();const location=useLocation();if(loading)return <div className="state" role="status">로그인 확인 중...</div>;if(error)return <div className="panel state"><p role="alert">{error}</p><button onClick={refresh}>다시 확인</button></div>;if(!user)return <div className="panel state"><h2>로그인이 필요합니다</h2><p>로그인 후 글을 쓰고 활동을 이어가세요.</p><Link className="button primary" to="/auth" state={{from:location.pathname}}>로그인</Link></div>;return children;}
