import { Link, NavLink, useNavigate, useLocation } from 'react-router-dom';
import { Cloud, Code2, Layers, Database, Shield, Users, MessageSquare } from 'lucide-react';
import { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { categories, categoryName } from '../data/categories';
import { isAdmin } from '../auth/permissions';

export function Icon({children,className=''}){return <span aria-hidden="true" className={`material-symbols-outlined ${className}`}>{children}</span>}
export function Logo(){return <img src="/logo.png" alt="난기류" className="h-9 w-auto object-contain"/>}
export function Header(){
 const {user,logout}=useAuth(), navigate=useNavigate(); const [q,setQ]=useState(''),[error,setError]=useState('');
 return <header className="fixed top-0 left-0 right-0 z-50 bg-[#0F172A] shadow-[0_1px_8px_rgba(0,0,0,0.15)]"><div className="h-16 max-w-7xl mx-auto px-4 sm:px-6 flex items-center justify-between gap-4">
 <div className="flex items-center gap-6 shrink-0"><Link to="/" aria-label="난기류 홈" className="flex items-center gap-3"><Logo/></Link><nav aria-label="주 메뉴" className="hidden lg:flex items-center gap-6"><NavLink to="/posts" className="font-label-md text-label-md text-slate-400 hover:text-white transition-colors">커뮤니티</NavLink><Link to="/posts?type=question" className="font-label-md text-label-md text-slate-400 hover:text-white transition-colors">Q&amp;A</Link><Link to="/posts?type=blog" className="font-label-md text-label-md text-slate-400 hover:text-white transition-colors">기술블로그</Link></nav></div>
 <form role="search" className="flex-1 max-w-[480px] hidden md:block" onSubmit={e=>{e.preventDefault();navigate(`/posts?q=${encodeURIComponent(q)}`)}}><div className="relative flex items-center w-full"><Icon className="absolute left-3.5 text-slate-400 text-[20px] pointer-events-none">search</Icon><input aria-label="게시글, 태그, 사용자 검색" className="w-full h-10 pl-10 pr-4 bg-[#1E293B] border border-slate-700/60 rounded-xl text-white placeholder-slate-400 font-body-sm text-body-sm focus:outline-none focus:border-primary-container focus:ring-1 focus:ring-primary-container transition-all" placeholder="게시글, 태그, 사용자 검색..." value={q} onChange={e=>setQ(e.target.value)}/></div></form>
 <div className="flex items-center gap-3 shrink-0"><Link to="/posts/new" className="hidden sm:inline-flex items-center gap-1.5 px-3.5 py-1.5 bg-primary-container hover:bg-primary text-on-primary font-label-md text-label-md rounded-lg transition-colors shadow-sm"><Icon className="text-[18px]">edit_square</Icon>글쓰기</Link>{isAdmin(user)&&<NavLink to="/admin" className="text-slate-300 hover:text-white text-label-md hidden sm:inline">관리자</NavLink>}<button type="button" title="알림" aria-label="알림" className="p-2 border-0 bg-transparent text-slate-400 hover:text-white rounded-lg transition-colors relative"><Icon className="text-[22px]">notifications</Icon><span className="absolute top-1.5 right-1.5 w-2 h-2 rounded-full bg-primary-container"/></button>{user?<><Link to="/profile" aria-label="내 프로필" className="flex items-center"><span className="w-8 h-8 rounded-full bg-primary flex items-center justify-center"><Icon className="text-on-primary text-[18px]">person</Icon></span></Link><button className="text-slate-400 hover:text-white bg-transparent border-0 p-1 text-xs hidden xl:inline" onClick={async()=>{try{await logout();navigate('/')}catch(e){setError(e.message)}}}>로그아웃</button></>:<Link to="/auth" className="text-slate-300 hover:text-white text-label-md">로그인</Link>}</div>
 </div>{error&&<div role="alert" className="error">{error}</div>}</header>
}
export function Footer(){return <footer><div><Link to="/"><Logo/></Link><span>개발자를 위한 지식 공유 및 성장 커뮤니티</span><small>함께 배우고, 질문하고, 성장해요.</small></div></footer>}
const icons={code:Code2,layers:Layers,database:Database,cloud:Cloud,shield:Shield,users:Users,message:MessageSquare};
export function CategoryIcon({id,size=20}){const Component=icons[id]||Code2;return <Component size={size}/>}
export function CategorySidebar({active=''}){return <aside className="w-full lg:w-60 flex-shrink-0 bg-surface-container-lowest rounded-xl shadow-sm p-3 reference-sidebar"><div className="px-3 pt-3 pb-2 font-label-sm text-label-sm text-on-surface-variant">카테고리</div><Link className={`flex items-center gap-3 px-3 py-2.5 rounded-xl font-label-md text-label-md ${!active?'bg-surface-container-low text-primary':'text-on-surface-variant hover:bg-surface'}`} to="/posts"><Icon className="text-[20px]">list</Icon>전체 게시글</Link>{categories.map(c=><Link key={c.id} className={`flex items-center gap-3 px-3 py-2.5 rounded-xl font-label-md text-label-md ${active===c.id?'bg-surface-container-low text-primary':'text-on-surface-variant hover:bg-surface'}`} to={`/posts?category=${c.id}`}><CategoryIcon id={c.icon}/>{c.name}</Link>)}<Link className="block bg-surface-container-low rounded-xl p-3 mt-5" to="/posts?type=question"><strong className="flex items-center justify-between text-primary text-label-md">Q&amp;A 바로가기 <Icon>arrow_forward</Icon></strong><p className="text-body-sm text-on-surface-variant mt-2 mb-0">해결되지 않는 에러나 아키텍처 고민을 동료 개발자들과 나눠보세요.</p></Link></aside>}
export const dateLabel=value=>value && !Number.isNaN(new Date(value).getTime()) ? new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium'}).format(new Date(value)) : '—';
export function PostCard({post,compact=false}){const author=post.author?.nickname||'알 수 없음';return <article className={compact?'p-4 sm:p-5 rounded-xl bg-surface hover:bg-surface-container-low transition-all duration-150 flex flex-col sm:flex-row sm:items-center justify-between gap-4 group cursor-pointer shadow-sm':'group bg-surface-container-lowest hover:bg-surface-bright rounded-xl p-4 sm:p-5 shadow-sm hover:shadow-md transition-all cursor-pointer'}><div className={compact?'flex items-start sm:items-center gap-3.5 min-w-0':'flex items-start gap-3.5 min-w-0'}><span className="w-10 h-10 rounded-full bg-surface-container-high flex-shrink-0 flex items-center justify-center text-primary overflow-hidden"><Icon className="text-[24px]">account_circle</Icon></span><div className="flex flex-col min-w-0 flex-1"><div className="flex items-center gap-2 text-on-surface-variant font-label-sm text-label-sm mb-0.5"><span className="font-headline-sm text-[13px] text-on-surface">{author}</span><span>·</span><span>{dateLabel(post.createdAt)}</span></div><Link className="font-headline-sm text-headline-sm text-on-surface group-hover:text-primary-container transition-colors" to={`/posts/${post.id}`}>{post.title}</Link><div className="flex items-center gap-1.5 mt-2 flex-wrap"><Link className="px-2 py-0.5 rounded-md bg-secondary-container text-primary font-label-sm text-label-sm" to={`/posts?category=${post.category}`}>{categoryName(post.category)}</Link>{(post.tags||[]).map(t=><Link className="px-2 py-0.5 rounded-md bg-secondary-container text-primary font-label-sm text-label-sm" key={t} to={`/posts?q=${encodeURIComponent(t)}`}>#{t}</Link>)}</div></div></div><div className={`flex items-center gap-4 font-label-md text-label-md text-on-surface-variant flex-shrink-0 ${compact?'self-end sm:self-center':'justify-end mt-4'}`}><span className="flex items-center gap-1.5"><Icon className="text-[18px]">favorite</Icon>{post.likeCount??0}</span><span className="flex items-center gap-1.5"><Icon className="text-[18px]">mode_comment</Icon>{post.commentCount??0}</span></div></article>}
export function AsyncState({state,children}){if(state.loading)return <div className="panel state" role="status">불러오는 중...</div>;if(state.error)return <div className="panel state"><p className="error" role="alert">{state.error.message}</p><button onClick={state.reload}>다시 시도</button></div>;return children}
export function Empty({children='아직 게시글이 없습니다.'}){return <div className="panel state muted">{children}</div>}
export function Protected({children}){const {user,loading,error,refresh}=useAuth();const location=useLocation();if(loading)return <div className="state" role="status">로그인 확인 중...</div>;if(error)return <div className="panel state"><p role="alert">{error}</p><button onClick={refresh}>다시 확인</button></div>;if(!user)return <div className="panel state"><h2>로그인이 필요합니다</h2><p>로그인 후 글을 쓰고 활동을 이어가세요.</p><Link className="button primary" to="/auth" state={{from:location.pathname}}>로그인</Link></div>;return children}
