import { Link } from 'react-router-dom';
import { api } from '../api';
import { useAsync } from '../hooks/useAsync';
import { AsyncState, CategoryIcon, Icon, PostCard } from '../components/common';
import { categories } from '../data/categories';

export default function Home(){
 const state=useAsync(()=>api.listPosts({sort:'popular',pageSize:3}));
 return <div className="max-w-[1100px] w-full mx-auto flex flex-col gap-8">
 <section className="w-full relative overflow-hidden rounded-2xl bg-gradient-to-br from-surface-container-low via-surface-container-lowest to-surface-container-high shadow-sm p-6 sm:p-10 lg:p-12">
 <div className="absolute -top-16 -right-16 w-80 h-80 rounded-full bg-primary/10 blur-3xl pointer-events-none"/><div className="absolute -bottom-16 left-1/3 w-64 h-64 rounded-full bg-tertiary-fixed-dim/20 blur-2xl pointer-events-none"/>
 <div className="relative z-10 grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
 <div className="lg:col-span-7 flex flex-col items-start space-y-5"><div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-secondary-container/60 text-primary font-label-md text-label-md"><span className="w-2 h-2 rounded-full bg-primary-container animate-pulse"/><span>개발자 지식 교류 플랫폼 난기류</span></div>
 <h1 className="font-display-hero text-display-hero text-on-surface tracking-tight leading-tight m-0">개발하는 모든 사람들을 위한 공간<br/><span className="text-primary-container">함께 배우고, 질문하고, 성장하세요.</span></h1>
 <p className="font-body-lg text-body-lg text-on-surface-variant max-w-xl leading-relaxed m-0">개발 관련 질문, 팁, 프로젝트 공유까지<br className="hidden sm:inline"/>개발자들의 생생한 기술 이야기가 모이는 커뮤니티입니다.</p>
 <div className="pt-2 flex flex-wrap items-center gap-3"><Link to="/posts" className="inline-flex items-center gap-2 px-6 py-3 bg-primary-container hover:bg-primary text-on-primary font-headline-sm text-headline-sm rounded-xl transition-all shadow-md hover:shadow-lg active:scale-95 group">지금 시작하기 <Icon className="text-body-lg group-hover:translate-x-1 transition-transform">arrow_forward</Icon></Link><Link to="/posts" className="inline-flex items-center gap-2 px-5 py-3 bg-surface-container hover:bg-surface-container-high text-on-surface font-label-md text-label-md rounded-xl transition-colors"><Icon className="text-[18px] text-primary-container">rate_review</Icon>게시글 둘러보기</Link></div></div>
 <div className="lg:col-span-5 flex justify-center items-center relative"><div className="relative w-full max-w-[380px] aspect-[4/3] flex items-center justify-center"><div className="w-full h-full bg-gradient-to-b from-surface-container-lowest to-surface-container rounded-2xl shadow-md p-5 flex flex-col justify-between relative overflow-hidden"><div className="absolute top-3 left-3 bg-[#0F172A] text-tertiary-fixed-dim px-3 py-1.5 rounded-lg text-code-snippet font-code-snippet shadow-sm flex items-center gap-1.5 animate-bounce" style={{animationDuration:'3s'}}><span className="text-[11px] text-white">clean_code.ts</span></div><div className="absolute top-3 right-3 w-8 h-8 rounded-lg bg-primary-container/15 flex items-center justify-center text-primary-container shadow-sm"><Icon className="text-[20px]">settings</Icon></div><div className="mt-8 w-full bg-[#0F172A] rounded-xl p-3 shadow-inner text-white flex flex-col gap-2"><div className="flex items-center gap-1.5"><span className="w-2.5 h-2.5 rounded-full bg-error"/><span className="w-2.5 h-2.5 rounded-full bg-surface-container-high"/><span className="w-2.5 h-2.5 rounded-full bg-tertiary-fixed-dim"/><span className="ml-2 font-code-snippet text-[10px] text-slate-400">난기류 Workspace</span></div><div className="font-code-snippet text-[11px] leading-relaxed text-slate-300"><span className="text-tertiary-fixed-dim">const</span> developer = {'{'}<br/>&nbsp;&nbsp;learning: <span className="text-primary-fixed-dim">true</span>,<br/>&nbsp;&nbsp;community: <span className="text-tertiary-fixed">'난기류'</span><br/>{'}'};</div></div><div className="flex items-end justify-between pt-2"><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-full bg-gradient-to-tr from-primary to-primary-container flex items-center justify-center text-on-primary shadow-sm"><Icon className="text-[28px]">terminal</Icon></div><div><div className="font-headline-sm text-headline-sm text-on-surface">함께 성장하기</div><div className="font-label-sm text-label-sm text-on-surface-variant">Q&amp;A · 블로그 · 네트워킹</div></div></div><div className="flex items-center gap-1 bg-surface-container-high px-2.5 py-1 rounded-full text-primary font-label-sm text-label-sm"><Icon className="text-[14px]">groups</Icon>14,200+</div></div></div></div></div>
 </div></section>
 <section className="w-full bg-surface-container-lowest rounded-2xl shadow-sm p-6 sm:p-8 flex flex-col gap-6"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="w-1.5 h-5 bg-primary-container rounded-full"/><h2 className="font-headline-lg text-headline-lg text-on-surface tracking-tight m-0">인기 게시글</h2></div><Link to="/posts?sort=popular" className="inline-flex items-center gap-1 font-label-md text-label-md text-primary-container hover:text-primary transition-colors group">전체보기 <Icon className="text-[16px] group-hover:translate-x-0.5 transition-transform">chevron_right</Icon></Link></div><div className="flex flex-col gap-3.5"><AsyncState state={state}>{(state.data?.items||[]).map(post=><PostCard key={post.id} post={post} compact/>)}</AsyncState></div></section>
 <section className="grid grid-cols-2 sm:grid-cols-4 gap-4">{categories.slice(0,4).map(c=><Link key={c.id} to={`/posts?category=${c.id}`} className="bg-surface-container-lowest rounded-xl p-4 flex items-center gap-3 hover:shadow-md transition-shadow text-on-surface"><span className="w-10 h-10 rounded-xl bg-surface-container flex items-center justify-center text-primary"><CategoryIcon id={c.icon}/></span><span><strong className="block font-headline-sm text-headline-sm">{c.name}</strong><small className="block text-on-surface-variant">{c.description}</small></span></Link>)}</section>
 </div>
}
