import { Link, useSearchParams } from 'react-router-dom';
import { api } from '../api';
import { useAsync } from '../hooks/useAsync';
import { AsyncState, CategorySidebar, Empty, PostCard, Icon } from '../components/common';
import { categoryName } from '../data/categories';
export default function Posts(){
 const [params,setParams]=useSearchParams(); const category=params.get('category')||'',q=params.get('q')||'',sort=params.get('sort')||'latest',type=params.get('type')||'',page=Math.max(1,Number(params.get('page'))||1);
 const state=useAsync(()=>api.listPosts({category,q,sort,type,page,pageSize:5}),[category,q,sort,type,page]);
 function change(values){const next=new URLSearchParams(params);for(const [k,v] of Object.entries(values))v?next.set(k,String(v)):next.delete(k);setParams(next)}
 return <div className="max-w-[1100px] w-full mx-auto flex flex-col lg:flex-row gap-5 lg:gap-6"><CategorySidebar active={category}/><section className="flex-1 w-full min-w-0"><div className="bg-surface-container-lowest rounded-xl shadow-sm p-4 sm:p-5 mb-4"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3"><div className="flex items-center gap-3"><h1 className="font-headline-lg text-headline-lg text-on-surface tracking-tight m-0">{q?`“${q}” 검색 결과`:category?categoryName(category):type==='question'?'Q&A':type==='blog'?'기술블로그':'전체 게시글'}</h1><span className="font-body-sm text-body-sm text-secondary bg-surface-container px-2.5 py-0.5 rounded-full">총 {state.data?.total??'…'}개</span></div><Link className="sm:hidden inline-flex items-center justify-center gap-1.5 px-4 py-2 bg-primary-container text-on-primary font-label-md text-label-md rounded-lg shadow-sm" to="/posts/new"><Icon className="text-[18px]">edit_square</Icon>글쓰기</Link></div><div className="flex items-center gap-2 pt-2 text-on-surface-variant">{[['latest','최신순'],['popular','인기순'],['comments','댓글순']].map(([id,label],i)=><span className="contents" key={id}>{i>0&&<span className="text-surface-dim font-body-sm text-body-sm">•</span>}<button className={`px-3 py-1.5 rounded-md border-0 transition-all ${sort===id?'font-headline-sm text-headline-sm text-primary-container bg-surface-container-low font-semibold':'font-body-md text-body-md text-secondary bg-transparent hover:text-on-surface hover:bg-surface-container-low'}`} onClick={()=>change({sort:id,page:null})}>{label}</button></span>)}{(q||type)&&<Link className="ml-auto text-label-md" to="/posts">전체보기</Link>}</div></div><AsyncState state={state}><div className="space-y-3">{state.data?.items.length?state.data.items.map(p=><PostCard key={p.id} post={p}/>):<Empty>조건에 맞는 게시글이 없습니다. <Link to="/posts/new">첫 글 작성하기</Link></Empty>}</div>{state.data&&<div className="pagination"><button disabled={page<=1} onClick={()=>change({page:page-1})}>이전</button><span>{page} / {Math.max(1,Math.ceil(state.data.total/5))}</span><button disabled={page*5>=state.data.total} onClick={()=>change({page:page+1})}>다음</button></div>}</AsyncState></section></div>
}
