import { Link, NavLink, Outlet } from 'react-router-dom';
import { LayoutDashboard, FileText, MessageSquare, Users, ShieldCheck } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { isMock } from '../../api';
const sections=[{path:'/admin',name:'운영 현황',Icon:LayoutDashboard,end:true},{path:'/admin/posts',name:'게시글 관리',Icon:FileText},{path:'/admin/comments',name:'댓글 관리',Icon:MessageSquare},{path:'/admin/users',name:'사용자 확인',Icon:Users}];
export default function AdminLayout(){
 const {user}=useAuth();
 return <div className="max-w-[1440px] mx-auto w-full flex flex-col md:flex-row gap-6 mb-12"><aside className="w-full md:w-60 shrink-0 bg-transparent flex flex-col justify-between py-2"><div><div className="flex items-center space-x-3 mb-6 px-1"><div className="w-9 h-9 rounded-xl bg-blue-50 border border-blue-100 flex items-center justify-center text-blue-600 shadow-xs"><ShieldCheck size={20}/></div><div><h2 className="text-sm font-bold text-slate-900 leading-tight m-0">관리자 센터</h2><p className="text-xs text-slate-500 m-0">난기류 커뮤니티 운영</p></div></div><nav aria-label="관리자 메뉴" className="space-y-1">{sections.map(({path,name,Icon,end})=><NavLink end={end} key={path} to={path} className={({isActive})=>`flex items-center space-x-3 px-3.5 py-2.5 rounded-lg text-sm transition-colors ${isActive?'font-semibold bg-[#eff6ff] text-blue-600':'font-medium text-slate-600 hover:bg-slate-100 hover:text-slate-900'}`}><Icon size={16}/><span>{name}</span></NavLink>)}</nav></div><div className="pt-8 border-t border-slate-200 mt-6 px-1"><div className="flex items-center space-x-3 mb-4"><div className="w-8 h-8 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center text-xs font-bold">{user.nickname.slice(0,1)}</div><div><div className="text-xs font-bold text-slate-900 leading-tight">{user.nickname}</div><div className="text-[11px] text-slate-500">관리자 계정</div></div></div><Link className="inline-flex items-center text-xs text-slate-500 hover:text-blue-600 transition-colors" to="/posts">← 커뮤니티로 돌아가기</Link></div></aside><section className="flex-1 min-w-0 space-y-6">{isMock&&<p className="text-xs font-medium text-blue-600 mb-2">데모 모드 · 이 브라우저의 mock 데이터를 관리합니다.</p>}<Outlet/></section></div>
}
